#!/bin/sh

mkdir -p /var/log/spin

start() {
        printf "Starting spin services: "
        /media/fat/spin/spin >> /var/log/spin/spin.log 2>&1 &
        [ $? = 0 ] && echo "OK" || echo "FAIL"
}

stop() {
        printf "Shutting down spin services: "
        kill -9 `pidof spin`
        [ $? = 0 ] && echo "OK" || echo "FAIL"
}

restart() {
        stop
        start
}

reload() {
        printf "Reloading spin config: "
        kill -HUP `pidof spin`
        [ $? = 0 ] && echo "OK" || echo "FAIL"
}

case "$1" in
  start)
        start
        ;;
  stop)
        stop
        ;;
  restart)
        restart
        ;;
  reload)
        reload
        ;;
  *)
        echo "Usage: $0 {start|stop|restart|reload}"
        exit 1
esac

exit $?